### ISSUE TITLE
gr-osmosdr make error [Sierra 10.12.3]

### ISSUE THREAD

**Issue by dmftd** [andresv/homebrew-gnuradio#10]
Running macOS Sierra (10.12.3), can't install gr-osmosdr:

Dave$ brew install gr-osmosdr --HEAD
==> Installing gr-osmosdr from andresv/gnuradio
==> Cloning git://git.osmocom.org/gr-osmosdr
Updating /Users/Dave/Library/Caches/Homebrew/gr-osmosdr--git
==> Checking out branch master
Warning: Calling Formula.factory is deprecated!
Use Formulary.factory instead.
/usr/local/Homebrew/Library/Taps/andresv/homebrew-gnuradio/gr-osmosdr.rb:20:in `python_path'
Please report this to the andresv/gnuradio tap!

==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gr-osmosdr/HEAD-ae686c4 -DCM
==> make
Last 15 lines from /Users/Dave/Library/Logs/Homebrew/gr-osmosdr/02.make:
cd /tmp/gr-osmosdr-20170203-99347-184yavb/build/lib && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBOOST_ALL_DYN_LINK -DHAVE_CONFIG_H=1 -DHAVE_FCD=1 -DLIBHACKRF_HAVE_DEVICE_LIST -DUSE_SSE2 -Dgnuradio_osmosdr_EXPORTS -I/tmp/gr-osmosdr-20170203-99347-184yavb/build/lib -I/tmp/gr-osmosdr-20170203-99347-184yavb/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib -I/usr/local/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/fcd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/file -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl_tcp -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/uhd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/hackrf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/bladerf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rfspace -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/redpitaya  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -Wall -Wextra -Wno-unused-parameter -Wsign-compare -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -o CMakeFiles/gnuradio-osmosdr.dir/bladerf/bladerf_common.cc.o -c /tmp/gr-osmosdr-20170203-99347-184yavb/lib/bladerf/bladerf_common.cc
[ 81%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/rfspace/rfspace_source_c.cc.o
cd /tmp/gr-osmosdr-20170203-99347-184yavb/build/lib && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBOOST_ALL_DYN_LINK -DHAVE_CONFIG_H=1 -DHAVE_FCD=1 -DLIBHACKRF_HAVE_DEVICE_LIST -DUSE_SSE2 -Dgnuradio_osmosdr_EXPORTS -I/tmp/gr-osmosdr-20170203-99347-184yavb/build/lib -I/tmp/gr-osmosdr-20170203-99347-184yavb/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib -I/usr/local/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/fcd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/file -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl_tcp -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/uhd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/hackrf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/bladerf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rfspace -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/redpitaya  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -Wall -Wextra -Wno-unused-parameter -Wsign-compare -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -o CMakeFiles/gnuradio-osmosdr.dir/rfspace/rfspace_source_c.cc.o -c /tmp/gr-osmosdr-20170203-99347-184yavb/lib/rfspace/rfspace_source_c.cc
[ 83%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/redpitaya/redpitaya_source_c.cc.o
cd /tmp/gr-osmosdr-20170203-99347-184yavb/build/lib && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBOOST_ALL_DYN_LINK -DHAVE_CONFIG_H=1 -DHAVE_FCD=1 -DLIBHACKRF_HAVE_DEVICE_LIST -DUSE_SSE2 -Dgnuradio_osmosdr_EXPORTS -I/tmp/gr-osmosdr-20170203-99347-184yavb/build/lib -I/tmp/gr-osmosdr-20170203-99347-184yavb/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib -I/usr/local/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/fcd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/file -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl_tcp -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/uhd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/hackrf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/bladerf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rfspace -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/redpitaya  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -Wall -Wextra -Wno-unused-parameter -Wsign-compare -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -o CMakeFiles/gnuradio-osmosdr.dir/redpitaya/redpitaya_source_c.cc.o -c /tmp/gr-osmosdr-20170203-99347-184yavb/lib/redpitaya/redpitaya_source_c.cc
[ 86%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/redpitaya/redpitaya_sink_c.cc.o
[ 88%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/redpitaya/redpitaya_common.cc.o
cd /tmp/gr-osmosdr-20170203-99347-184yavb/build/lib && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBOOST_ALL_DYN_LINK -DHAVE_CONFIG_H=1 -DHAVE_FCD=1 -DLIBHACKRF_HAVE_DEVICE_LIST -DUSE_SSE2 -Dgnuradio_osmosdr_EXPORTS -I/tmp/gr-osmosdr-20170203-99347-184yavb/build/lib -I/tmp/gr-osmosdr-20170203-99347-184yavb/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib -I/usr/local/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/fcd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/file -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl_tcp -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/uhd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/hackrf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/bladerf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rfspace -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/redpitaya  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -Wall -Wextra -Wno-unused-parameter -Wsign-compare -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -o CMakeFiles/gnuradio-osmosdr.dir/redpitaya/redpitaya_common.cc.o -c /tmp/gr-osmosdr-20170203-99347-184yavb/lib/redpitaya/redpitaya_common.cc
cd /tmp/gr-osmosdr-20170203-99347-184yavb/build/lib && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DBOOST_ALL_DYN_LINK -DHAVE_CONFIG_H=1 -DHAVE_FCD=1 -DLIBHACKRF_HAVE_DEVICE_LIST -DUSE_SSE2 -Dgnuradio_osmosdr_EXPORTS -I/tmp/gr-osmosdr-20170203-99347-184yavb/build/lib -I/tmp/gr-osmosdr-20170203-99347-184yavb/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib -I/usr/local/include -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/fcd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/file -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rtl_tcp -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/uhd -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/hackrf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/bladerf -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/rfspace -I/tmp/gr-osmosdr-20170203-99347-184yavb/lib/redpitaya  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -Wall -Wextra -Wno-unused-parameter -Wsign-compare -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -o CMakeFiles/gnuradio-osmosdr.dir/redpitaya/redpitaya_sink_c.cc.o -c /tmp/gr-osmosdr-20170203-99347-184yavb/lib/redpitaya/redpitaya_sink_c.cc
[ 90%] Linking CXX shared library libgnuradio-osmosdr.dylib
cd /tmp/gr-osmosdr-20170203-99347-184yavb/build/lib && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_link_script CMakeFiles/gnuradio-osmosdr.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 0.1.5 -o libgnuradio-osmosdr.0.1.5git.dylib -install_name /tmp/gr-osmosdr-20170203-99347-184yavb/build/lib/libgnuradio-osmosdr.0.1.5git.dylib CMakeFiles/gnuradio-osmosdr.dir/source_impl.cc.o CMakeFiles/gnuradio-osmosdr.dir/sink_impl.cc.o CMakeFiles/gnuradio-osmosdr.dir/ranges.cc.o CMakeFiles/gnuradio-osmosdr.dir/device.cc.o CMakeFiles/gnuradio-osmosdr.dir/time_spec.cc.o CMakeFiles/gnuradio-osmosdr.dir/fcd/fcd_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/file/file_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/file/file_sink_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/rtl/rtl_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/rtl_tcp/rtl_tcp_source_f.cc.o CMakeFiles/gnuradio-osmosdr.dir/rtl_tcp/rtl_tcp_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/uhd/uhd_sink_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/uhd/uhd_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/hackrf/hackrf_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/hackrf/hackrf_sink_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/bladerf/bladerf_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/bladerf/bladerf_sink_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/bladerf/bladerf_common.cc.o CMakeFiles/gnuradio-osmosdr.dir/rfspace/rfspace_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/redpitaya/redpitaya_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/redpitaya/redpitaya_sink_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/redpitaya/redpitaya_common.cc.o /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libgnuradio-runtime.dylib /usr/local/lib/libgnuradio-pmt.dylib /usr/local/lib/libgnuradio-blocks.dylib /usr/local/lib/libgnuradio-fcd.dylib /usr/local/lib/librtlsdr.dylib /usr/local/lib/libgnuradio-uhd.dylib /usr/local/lib/libuhd.dylib /usr/local/lib/libhackrf.dylib /usr/local/lib/libbladeRF.dylib 
cd /tmp/gr-osmosdr-20170203-99347-184yavb/build/lib && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_symlink_library libgnuradio-osmosdr.0.1.5git.dylib libgnuradio-osmosdr.0.1.5git.dylib libgnuradio-osmosdr.dylib
[ 90%] Built target gnuradio-osmosdr
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/andresv/homebrew-gnuradio/issues

**Comment by andresv** [comment]
Should be now fixed.
