### ISSUE TITLE
Make errors on Mac OS Sierra using brew

### ISSUE THREAD

**Issue by J-Iszatt** [andresv/homebrew-gnuradio#11]
I get strange compiler errors on Mac Os Sierra on following this tutorial : https://github.com/andresv/homebrew-gnuradio

> justin$ brew install gr-osmosdr gr-baz --HEAD
> ==> Installing gr-osmosdr from andresv/gnuradio
> ==> Cloning git://git.osmocom.org/gr-osmosdr
> Updating /Users/justin/Library/Caches/Homebrew/gr-osmosdr--git
> ==> Checking out branch master
> Warning: Calling Formula.factory is deprecated!
> Use Formulary.factory instead.
> /usr/local/Homebrew/Library/Taps/andresv/homebrew-gnuradio/gr-osmosdr.rb:20:in `python_path'
> Please report this to the andresv/gnuradio tap!
> 
> ==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CX
> ==> make
> Last 15 lines from /Users/justin/Library/Logs/Homebrew/gr-osmosdr/02.make:
>   cmd = { 0x09, htonl(direct_samp) };
>         ^
> /tmp/gr-osmosdr-20170622-14519-1e6x46o/lib/rtl_tcp/rtl_tcp_source_c.cc:307:9: error: expected expression
>   cmd = { 0x0a, htonl(offset_tune) };
>         ^
> /tmp/gr-osmosdr-20170622-14519-1e6x46o/lib/rtl_tcp/rtl_tcp_source_c.cc:311:9: error: expected expression
>   cmd = { 0x0e, htonl(bias_tee) };
>         ^
> /tmp/gr-osmosdr-20170622-14519-1e6x46o/lib/rtl_tcp/rtl_tcp_source_c.cc:570:9: error: expected expression
>   cmd = { 0x08, htonl(automatic) };
>         ^
> 4 errors generated.
> make[2]: *** [lib/CMakeFiles/gnuradio-osmosdr.dir/rtl_tcp/rtl_tcp_source_c.cc.o] Error 1
> make[1]: *** [lib/CMakeFiles/gnuradio-osmosdr.dir/all] Error 2
> make: *** [all] Error 2
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/andresv/homebrew-gnuradio/issues
> 
> These open issues may also help:
> gr-osmosdr make error [Sierra 10.12.3] https://github.com/andresv/homebrew-gnuradio/issues/10
> build justin$ 

I honestly have no clue why this happens and am wondering if it's about something i have been doing wrong (had some probs with cheetah.. with python3 and had to come back to 2.7.13) or if this is a platform problem..

Help would greatly aprreciated

**Comment by rmd6502** [comment]
Same error, osx 10.12b6 
[02.zip](https://github.com/andresv/homebrew-gnuradio/files/1184160/02.zip)

**Comment by andresv** [comment]
I do not have Sierra but #12 is definitely important and probably fixes this issue.
